//! The published MHFE vectors as the self-checks replay them: inputs, container, recovery and
//! the salt and Argon2id key of every round. Generated by scripts/generate-published-rounds.py
//! from tests/fixtures/suite3-vectors and tests/fixtures/suite4-vectors (the specification's
//! vectors/suite3 and vectors/suite4); do not edit. The unit test
//! published_round_table_equals_the_fixtures compares every value with the fixtures.

use super::known_answers::{PublishedReading, PublishedRound, PublishedVector};
use crate::self_check::hex;

pub(super) static PUBLISHED: [PublishedVector; 27] = [
    PublishedVector {
        name: "ambiguous-12-21",
        same_length: false,
        startup: true,
        phrase: "essence drama mule dolphin bitter rain abandon abandon able human mule relax",
        password: "public test password",
        password_nfkd: b"public test password",
        pim: 0,
        memory_level: 0,
        container: "music awkward broken sing mass birth praise identify example industry rubber sister six initial funny icon able disorder dish glide eternal junk plate flat",
        recovery: &[
            PublishedReading {
                words: 12,
                verified: true,
                phrase: "essence drama mule dolphin bitter rain abandon abandon able human mule relax",
            },
            PublishedReading {
                words: 21,
                verified: true,
                phrase: "essence drama mule dolphin bitter rain abandon abandon able human mule relax forest bleak chest march april confirm pill east sock",
            },
            PublishedReading {
                words: 24,
                verified: false,
                phrase: "essence drama mule dolphin bitter rain abandon abandon able human mule relax forest bleak chest march april confirm pill east sock simple dress sand",
            },
        ],
        rounds: [
            PublishedRound {
                salt: hex("b782b85850ede6c25b9c1ac1ad02a4b1"),
                key: hex("c52b144633192893613014f7cc237973b032da4d1616343696125365a6ef46ad"),
            },
            PublishedRound {
                salt: hex("6f5b83c5896fdfe90b1514e7ea34707e"),
                key: hex("5dadbfc0e76bc5751dc948725f7ee679d29135834ce73e0b7448b154db9b496a"),
            },
            PublishedRound {
                salt: hex("66fb32e560b84b46602ffbe8e3e6b01f"),
                key: hex("dbe619f86bf8dc6af20801b4bc85e4eee60fc9bfa3aef58b6dcd9979a237446b"),
            },
            PublishedRound {
                salt: hex("f2dec823b0a4888f806e61a9bb4b9abe"),
                key: hex("9459201d8ae570a033817fc63d5827a691deffbefbf3f1552475b6ed29f69f7d"),
            },
            PublishedRound {
                salt: hex("cbedce9402cc0edf105c2b987313a998"),
                key: hex("7cb7bb192b8f5d1ff432d776dc4a976fea9d051d117dcd8d3e3067b85c29d7ad"),
            },
            PublishedRound {
                salt: hex("aeb639f13e01dce2818edc7ee2aea340"),
                key: hex("a5134e69ae2c7c033c4cc372132ba8f59f4b428bed5d276bc78462555847df9e"),
            },
            PublishedRound {
                salt: hex("996f531095b3c6212976cdb8aabedb92"),
                key: hex("f53e8edf954070410d93573c9d1d254eec08fd8f1599f5dc8625d8db1fbb95a8"),
            },
            PublishedRound {
                salt: hex("ed4b4c9a4ef43e131088207cabaa2413"),
                key: hex("bc2e2c3d758cd725de3e821207759c2fb69ad4d56966ef1474c95e28f5dce41b"),
            },
            PublishedRound {
                salt: hex("219b586ec720929d396aed9f0bea09b5"),
                key: hex("7dd45d6258fa75d482775e82018b8eb8fade2862bf3ca19b8c3aa7bfa0519cd2"),
            },
            PublishedRound {
                salt: hex("47431b607a4cf348d98b6785d9d62d29"),
                key: hex("695a8ce5af1684d72dde4351c11db19fa72a68b346142e02a0d079ff9df3d5e9"),
            },
            PublishedRound {
                salt: hex("5b15f65a7f8ea153b8241d7e142104a2"),
                key: hex("f7ebf0486c700ba2cc1f6b85f9fceda2dedadc0746ba3b565fc181963c1cbe37"),
            },
            PublishedRound {
                salt: hex("22d4afe8c56b849882daaaf650d9f62e"),
                key: hex("0d863eca79749ef24a900ed124291e99b69170eeaccd23a022e5ef1a1551cc2e"),
            },
        ],
    },
    PublishedVector {
        name: "nonzero-12",
        same_length: false,
        startup: false,
        phrase: "legal winner thank year wave sausage worth useful legal winner thank yellow",
        password: "audit probe password 2026",
        password_nfkd: b"audit probe password 2026",
        pim: 0,
        memory_level: 0,
        container: "tag elite catalog notable garden balcony piece demise rival position tourist report state top royal setup exhibit treat smooth grace keen inquiry custom struggle",
        recovery: &[
            PublishedReading {
                words: 12,
                verified: true,
                phrase: "legal winner thank year wave sausage worth useful legal winner thank yellow",
            },
        ],
        rounds: [
            PublishedRound {
                salt: hex("744f2c3930b8bed6b1b4bc3b72ec0182"),
                key: hex("eec679c1356d5d4c130e651fb5469cd37e68decfd97667161ab1d5c08b347ba6"),
            },
            PublishedRound {
                salt: hex("f2c11396bb010a497cdee53781d72e61"),
                key: hex("4bd75ae142d1f677c84a6ccd0863bba7afbd15f555fcad1755bf74740b21cf6c"),
            },
            PublishedRound {
                salt: hex("6da088af3a74120545826ed0c6b90c52"),
                key: hex("81a2e93dd2124c70eed5b38a396e7e51b0fb5e9939c404fb9473684dd1ea760c"),
            },
            PublishedRound {
                salt: hex("a9f80349ab940d4e5171956d864d3e6e"),
                key: hex("3c6cc90b27cc555085801ce1bd09dab415cb832c3d8adc40da1341299360684e"),
            },
            PublishedRound {
                salt: hex("6ada58341d3422f9d89375b88aac5039"),
                key: hex("1d52a4f8f0f02639e012ed9cc5ba20f8aaed4884a0a831f6e46463e242bfaec7"),
            },
            PublishedRound {
                salt: hex("2a2aa1df6ef83c16c07b9a54c8671d3f"),
                key: hex("da849dd57d4db5301714afd6c5f99b97d097f2b0876ffce67516dab0b0da162e"),
            },
            PublishedRound {
                salt: hex("1b8675dade08644af69b8d3acb8e0866"),
                key: hex("72049a0d4b1afff4a2be42fe7ffd90bb1b17589fd242a3142cd9df109f856ee3"),
            },
            PublishedRound {
                salt: hex("e13c7220a9aa93c7fe6a387a3b43643a"),
                key: hex("507e9ef92f0b5ae0372c3a204e03891c55151ed23f41ee665a37121b3cc07287"),
            },
            PublishedRound {
                salt: hex("3d36b2b5c4d4a1efea4b40651331a7aa"),
                key: hex("9f0ef735dc92e50c66c583b772d6ea39cc4c37a07dd5e848e9968c23f614d9ae"),
            },
            PublishedRound {
                salt: hex("82bc6ca56abde39a421d7297d3bfb7cb"),
                key: hex("6e46b7f0f5010d970e6ecb749c5073ee79255da78e25cabc7432232d50c981a5"),
            },
            PublishedRound {
                salt: hex("57d467b9293d578b6ac5db39b6d4a6f1"),
                key: hex("d8e2db279cd4b2fd2c88b61eb26b49c8d47b3064d7c5deca355d4310575a262a"),
            },
            PublishedRound {
                salt: hex("260278024ef892ba2ed009493a7b54a7"),
                key: hex("052267757e6c302dd419848334359013e8827d76aa533d2b55ab1381c30af675"),
            },
        ],
    },
    PublishedVector {
        name: "nonzero-15",
        same_length: false,
        startup: true,
        phrase: "legal winner thank year wave sausage worth useful legal winner thank year wave sausage wise",
        password: "audit probe password 2026",
        password_nfkd: b"audit probe password 2026",
        pim: 0,
        memory_level: 0,
        container: "allow fly gasp kitten ability clinic motor street buzz word liberty ugly digital attend beef obscure monster miracle bulk expect loan prefer legend frame",
        recovery: &[
            PublishedReading {
                words: 15,
                verified: true,
                phrase: "legal winner thank year wave sausage worth useful legal winner thank year wave sausage wise",
            },
        ],
        rounds: [
            PublishedRound {
                salt: hex("a3ab679a59a731492ec8e9c749008c74"),
                key: hex("4eb0c0d2feb8f39a0905176843df8e78c56f2043a64beb3d4cd1bc28a139bd73"),
            },
            PublishedRound {
                salt: hex("14c4a3bd680451c3299cb6cb00528eee"),
                key: hex("3b84d53ddb5cb33bb6c5230ebcdec1fc51d99b5c6b7a3c8d09f7ef428baa86a6"),
            },
            PublishedRound {
                salt: hex("266f4d2d4feb516d0001bc94840f1aa5"),
                key: hex("4faab0c65478a36b63aaa186024453c4436d45c8b33f62aa02f46c9944f7bca3"),
            },
            PublishedRound {
                salt: hex("e248d1aa0e80110009e19bdc64edb62f"),
                key: hex("cb417093924fc67a613caa59ed861c7ca684f382b4d53af0701b0fa7171267b6"),
            },
            PublishedRound {
                salt: hex("a9efd446203e6c5bde2f845f84628d5d"),
                key: hex("b30015b5ab1e443e50c0ea48eb6c6853df1773b90b679aae212cde7c68b7d133"),
            },
            PublishedRound {
                salt: hex("cf520e93a38c398c4c48b98fe998ecf9"),
                key: hex("bb3c896901ab9e5fad35c0f8c8da270b19bb1282beb755a399e89daea1024f5d"),
            },
            PublishedRound {
                salt: hex("0149782f70f06a14eff6ea7f2bde041c"),
                key: hex("bf0ddf1928a17eb6a5390a453006d078b3d63f8d621b90c8c7941f9a877cba47"),
            },
            PublishedRound {
                salt: hex("eacc19f06211bb3d72acd161329ab6c5"),
                key: hex("4c8ac0ee8979ec2f27252c36ce97f64c8ea35ec6e10862b32439bc8de46dc4c7"),
            },
            PublishedRound {
                salt: hex("a05f40bcac262598d1abd3ae0b0ef087"),
                key: hex("b6d2cc559d4bc81da550f26f8355216b1106e428a3a40c39df5dffd6db3f13d0"),
            },
            PublishedRound {
                salt: hex("d4c23f5c1081cac55559a9b4a30cefae"),
                key: hex("cfafd523f7dece99f7aed87e8323a940b78c567d9b3f664b9e539f245a1f9ed3"),
            },
            PublishedRound {
                salt: hex("1be5491e58661ab7f243d85191149e71"),
                key: hex("64fa55402eb014d0e6b19fd961ce1e1d69a678503121da7801368e90ad0a9559"),
            },
            PublishedRound {
                salt: hex("125f9ed8be8fdf30e1b6c396f6025e82"),
                key: hex("714033710253ca879f7d91cd130abef2ed33adf779d938a3a26b9d91cbc851ed"),
            },
        ],
    },
    PublishedVector {
        name: "nonzero-18",
        same_length: false,
        startup: false,
        phrase: "letter advice cage absurd amount doctor acoustic avoid letter advice cage absurd amount doctor acoustic avoid letter always",
        password: "audit probe password 2026",
        password_nfkd: b"audit probe password 2026",
        pim: 0,
        memory_level: 0,
        container: "rice nerve grab enlist jungle evoke jealous plunge better come depth pride change purity actual mistake friend inhale offer fever away ribbon scale artist",
        recovery: &[
            PublishedReading {
                words: 18,
                verified: true,
                phrase: "letter advice cage absurd amount doctor acoustic avoid letter advice cage absurd amount doctor acoustic avoid letter always",
            },
        ],
        rounds: [
            PublishedRound {
                salt: hex("7a69c02900af72effebd8901508f8e8b"),
                key: hex("338a18387e98345f516fc985f5d5a7572f4f6369ede46cb5dc058c0f008f79c8"),
            },
            PublishedRound {
                salt: hex("5c59040b98316f70aee4fec63d27f4b6"),
                key: hex("f5617f85fe9f303d260ad0605f31486efe6ffde2cc1d1dd21ce7b6ced64a7fb3"),
            },
            PublishedRound {
                salt: hex("9188c02dc6930c057907c83b28221bfe"),
                key: hex("56e251bc5d34e292d23f58599c78150795b1b1525a46e37401c03e3a4780a39b"),
            },
            PublishedRound {
                salt: hex("ee8c0818ca06ada65a8265c35dd3fb02"),
                key: hex("710b3833841357f08b6326fafc90d568f9186b624ff3ed596d75fc939270c76c"),
            },
            PublishedRound {
                salt: hex("c6cef3dc3316d98c47bc8fce397bc58a"),
                key: hex("3e007a29fd31257adb98211628bfc42a83cfff7f8556668f0b2082887f5bf696"),
            },
            PublishedRound {
                salt: hex("427de4b8360a5356e569456b78e8d6e5"),
                key: hex("58733f5ebeadc48d6a1943ddbe1854f32ecb9f3d7f5bf7ebbf0b9d896b5ae15c"),
            },
            PublishedRound {
                salt: hex("65144ba9bea4a84822fefef8860b0b7f"),
                key: hex("9cd86dbf6eaa5de140245468aaba71766457b8e4abdfde6081104d1ec26617d2"),
            },
            PublishedRound {
                salt: hex("cdd68fd60713a282c0d4ec580bf4ea15"),
                key: hex("cf7b1b781d071cf11d030e1aec71fb958a44433859de494ad2c17be97c55cf9e"),
            },
            PublishedRound {
                salt: hex("f3da67fda77eb32b9e024e490d66ea81"),
                key: hex("b6f19b13a2cfd8e6611e97d3c80926288e11fe53bd85eb478e151bb30c4e362a"),
            },
            PublishedRound {
                salt: hex("0735b2d1a402014198e9f8ede47c8698"),
                key: hex("58f64ead9b7d57cf9387513623be34535f94f1f03aea321f2e9528e77b8aec8f"),
            },
            PublishedRound {
                salt: hex("a36d7203fe7d94b97433cce79eef2162"),
                key: hex("c50eaedaa29e745d07ab50bbcf6fe6661b585f7e57f44c004e7edfe577df82ca"),
            },
            PublishedRound {
                salt: hex("613dd4a1e138b61171daa8947f45a4ed"),
                key: hex("ff26c1e946ae0605f3ae05505232ea2cd154403c031dae9e34aafe740c42c6d5"),
            },
        ],
    },
    PublishedVector {
        name: "nonzero-21",
        same_length: false,
        startup: false,
        phrase: "letter advice cage absurd amount doctor acoustic avoid letter advice cage absurd amount doctor acoustic avoid letter advice cage absurd apart",
        password: "audit probe password 2026",
        password_nfkd: b"audit probe password 2026",
        pim: 0,
        memory_level: 0,
        container: "giant keep embrace angry veteran good void squeeze choice cement miss surround company extend cotton mammal arrive dish reopen wild impact flavor summer forum",
        recovery: &[
            PublishedReading {
                words: 21,
                verified: true,
                phrase: "letter advice cage absurd amount doctor acoustic avoid letter advice cage absurd amount doctor acoustic avoid letter advice cage absurd apart",
            },
        ],
        rounds: [
            PublishedRound {
                salt: hex("1f9b78b4e394a0d7bccec5bca70c8bce"),
                key: hex("36c46644ce8bf89d70e17700563919e2a83977ff68f29d192600c7fbdcdd3278"),
            },
            PublishedRound {
                salt: hex("8e135258c4b5004b78a5f545c2439e71"),
                key: hex("1e5bbd804aee7865f5fe6265f34aa3577d12b032b75ec3fcda26bab2ec006f19"),
            },
            PublishedRound {
                salt: hex("47991750ae0466b5ae7b07829aec3fee"),
                key: hex("5010e485574eefd7ca0e369c7ad021ff88edf86ee9450f62d7374c20ff1e915a"),
            },
            PublishedRound {
                salt: hex("87ce8a2a9299f823177c3168c23a4bc0"),
                key: hex("15f76a052d5237a6001f3a2c2af50a2d30595c12972d80bbb376c4ba53fe6d95"),
            },
            PublishedRound {
                salt: hex("a3deef14a6a41bc45c87095ac87dff2b"),
                key: hex("15cd58dc682132468e233357efb97c56b56cec49c6b84fe6c9d2c7c7040251fd"),
            },
            PublishedRound {
                salt: hex("18c9d6a2150af1175d24ab82a5b37e2e"),
                key: hex("f80444d9ffd9ba886671824d29c810baa30132f35e8b124d04487dd32e63fad3"),
            },
            PublishedRound {
                salt: hex("58b05293027ceacb88b4abeb25dceac2"),
                key: hex("bb49b14a9c29061911c3600b2814ffc55394a1d25bf9ec370fb6f54b64d64c2c"),
            },
            PublishedRound {
                salt: hex("6a8941bc0cffe294c38a5c7e32802180"),
                key: hex("8b36285505f41166d33db0f9b7e5360d5a31bc3f724198bdcb91e12258256d57"),
            },
            PublishedRound {
                salt: hex("70c697432608ef18ca49a0f5d78bfdfe"),
                key: hex("a3c068827d4e84d2e6d8b5149892ae2306b9b2d7f3dcea40e1c2c3e994ceee80"),
            },
            PublishedRound {
                salt: hex("f25c6e31f036089de8e0dc3d8f350d89"),
                key: hex("6c3f2b4ab359c0e3314fe34a91878b61456e74adc29b609d1bcf9136027a24d1"),
            },
            PublishedRound {
                salt: hex("bdd3f3bd8de29d1db07b661661adfaff"),
                key: hex("4d2a9c12dab91efb2eda0edf3578210f56f67d522899343fd9bb6f7dc629a87f"),
            },
            PublishedRound {
                salt: hex("a6a12e11418b908ac0564d32f1bff19f"),
                key: hex("4948a9b1e8a095d0998c681491352598e5fba401a05ffe3df965e6958fdda3f5"),
            },
        ],
    },
    PublishedVector {
        name: "nonzero-24",
        same_length: false,
        startup: false,
        phrase: "legal winner thank year wave sausage worth useful legal winner thank year wave sausage worth useful legal winner thank year wave sausage worth title",
        password: "audit probe password 2026",
        password_nfkd: b"audit probe password 2026",
        pim: 0,
        memory_level: 0,
        container: "human library arrive hurdle tag dress oxygen fix weasel foam legend gas bike swallow base dizzy trash weird motor snake affair muscle faint blind",
        recovery: &[
            PublishedReading {
                words: 24,
                verified: false,
                phrase: "legal winner thank year wave sausage worth useful legal winner thank year wave sausage worth useful legal winner thank year wave sausage worth title",
            },
        ],
        rounds: [
            PublishedRound {
                salt: hex("7cd225fa3fef15e34985b8a360839634"),
                key: hex("5de7556517cdbfa6f4459846de0cb2668e99247091282cf2f4c5a88d4b326fed"),
            },
            PublishedRound {
                salt: hex("0600d6a8680fbc07501d23a551d845ab"),
                key: hex("9d44249662beedab570d4e6735f18713025e3bb5c21c35ca27a25f19e9d4734b"),
            },
            PublishedRound {
                salt: hex("cf72b79e337d0fb557f065aa01b28d6b"),
                key: hex("8c676c11491ebd1d4d9d35e8d6d7189e500a513292b125b736d9246d1013d5f1"),
            },
            PublishedRound {
                salt: hex("b68d16d9eddf38a61bd6ca4782b068ea"),
                key: hex("911968e6392a905ae85ad0b2e0fee8c4dc0f9cd88905cddc290e8b6eef310891"),
            },
            PublishedRound {
                salt: hex("b172d7a1ffac0ceef4762404a126e1a0"),
                key: hex("42163bb5f229c2feefb08326593f0cf77c1406f6a33335b85676e473948306f7"),
            },
            PublishedRound {
                salt: hex("13fd4f58ac501aa74495377359f1f05e"),
                key: hex("1f59f608a8ba8120788248be9efc29ea720cbacd71319dcdc63cb070b84c1b8e"),
            },
            PublishedRound {
                salt: hex("3c9b9023504453e7207352f725e1abe7"),
                key: hex("9e166bc02db5b2399e9fa404bdb23c133e4628291c97d67cdc791069bf58ec7c"),
            },
            PublishedRound {
                salt: hex("15eb02e34a8c7e5083894231d87077e4"),
                key: hex("c9518a9cff70f04380c5f7bc6059050dd5135825775e4ac3f88d43ac7c878ec9"),
            },
            PublishedRound {
                salt: hex("bfdf10aa4a37c9d2ba48920b7fb9c673"),
                key: hex("1b42819b9a397a296c20973d393894241cb537850f173b063fadf0c08704df2d"),
            },
            PublishedRound {
                salt: hex("bc17c5fea88551a1d4ea647a8785de1f"),
                key: hex("6d0946697cdf041e3d9fb323b3beeeb02a182d4b42e1a7d1c4d11edadd1745f8"),
            },
            PublishedRound {
                salt: hex("d861d865fbd85ca132fe5b687ef5164c"),
                key: hex("fe20511bee691c9d5aeb453c9241cc41aa3da8b2c33a60962a5cb86f18809c03"),
            },
            PublishedRound {
                salt: hex("e3769f8460b90de003b2a3d72b82e62b"),
                key: hex("8bdd2e2d4d560516d550d209fe56b7fa3ad12accd451ecf57f142bc75521e5c4"),
            },
        ],
    },
    PublishedVector {
        name: "spaces-password",
        same_length: false,
        startup: false,
        phrase: "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about",
        password: "  public   test password  ",
        password_nfkd: b"  public   test password  ",
        pim: 0,
        memory_level: 0,
        container: "course symbol timber flat decide pulp whisper immense cart shield electric purpose bid review ivory pluck prefer ready crawl subject bus fuel solid space",
        recovery: &[
            PublishedReading {
                words: 12,
                verified: true,
                phrase: "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about",
            },
        ],
        rounds: [
            PublishedRound {
                salt: hex("9d84a9f7b0fa2bfda1203a2afc48a6cf"),
                key: hex("578ee1fc90ce0644a99e2a6e9302cf1a4c7b85b7c978f6d1c61325418c2b30fe"),
            },
            PublishedRound {
                salt: hex("3da27acdee6895a5715b842df65d10dc"),
                key: hex("624a8f9c48a7ed9646e9d2bb56f8af65f238d5fbc3e63faef6d0aecf5978485d"),
            },
            PublishedRound {
                salt: hex("c71caadc56ac51d382856fd4ee6b8de5"),
                key: hex("0ac28aeaf62ec141a5459d75a8bc0a36a4ca2f8712f0e751ca531f3e6fe5ed81"),
            },
            PublishedRound {
                salt: hex("269617a45d7acb0d1d82d600de0ef562"),
                key: hex("4b758c9d7f0c5ed917c46b105e8f56c485f9c6bf04c54e7dd53ca9783a21f17c"),
            },
            PublishedRound {
                salt: hex("61d1537471f27d6b3c321b6b7ab30cc1"),
                key: hex("7b079138fd37bfcd976b5d46ecc2886eafefca69eaa5ea30467c2544718551ba"),
            },
            PublishedRound {
                salt: hex("f4e17e9594c1321bb756a67656cd3336"),
                key: hex("06a54ccf036df517883542b8d92627372fd6858875ca77731a902cd366469669"),
            },
            PublishedRound {
                salt: hex("b1e08f5aeb08d44a0039ef6b44592213"),
                key: hex("e7eb851595d4290c00c0ded1d5c7a58131a6eeb60353c636fe76a25e95cceeca"),
            },
            PublishedRound {
                salt: hex("13eaf7973bf495a9bf2f18a6e20112b1"),
                key: hex("2bad3ef212b524123bcc77e3c1c5ee524d545d79e28bc8f788d6d5b96701f173"),
            },
            PublishedRound {
                salt: hex("299a9b4ff1bb35fcffbccd84cd9829e2"),
                key: hex("20d3a5c9f111c3329d5f9a2aa63de71428894af0857c0beebf1e6a2714c8a586"),
            },
            PublishedRound {
                salt: hex("335ec5604c009ad17a6bc86b4b200cb6"),
                key: hex("b81b4c172dbe92c1e4beeb77f8ea48835126fa6a1d2c06f417216248eb7a74e8"),
            },
            PublishedRound {
                salt: hex("5eb1bdef5f3e0f8576a7a3467b03c1bd"),
                key: hex("6b0764e9d595fdbdb403de802dddb952cffdbc12a19d32f1c89fc9abd31c7592"),
            },
            PublishedRound {
                salt: hex("b18bfdaff588d43c3170c59654e5bc42"),
                key: hex("997ee87d40a3aeacba1bd2aceef9e979918baaee8439604b7396e758aee806f9"),
            },
        ],
    },
    PublishedVector {
        name: "unicode-password",
        same_length: false,
        startup: true,
        phrase: "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about",
        password: "Caf\u{e9} \u{fb01} \u{ff30}\u{212b}\u{2460} \u{1f510} \u{439}",
        password_nfkd: b"Cafe\xcc\x81 fi PA\xcc\x8a1 \xf0\x9f\x94\x90 \xd0\xb8\xcc\x86",
        pim: 0,
        memory_level: 0,
        container: "leopard pear jazz half wife peace cup electric rely because cable road consider oblige roast feature foam must mask wagon before smooth sheriff rain",
        recovery: &[
            PublishedReading {
                words: 12,
                verified: true,
                phrase: "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about",
            },
        ],
        rounds: [
            PublishedRound {
                salt: hex("9d84a9f7b0fa2bfda1203a2afc48a6cf"),
                key: hex("167ae14745a6ff574cbafff9baefc7d2a8040db3a1204d285e36357bd175a4af"),
            },
            PublishedRound {
                salt: hex("72579e5cd93f1ccba0a40099982dd225"),
                key: hex("5e836de6e3bb46492e7f907078a4c19a372a6769d1b428769934328166de4d74"),
            },
            PublishedRound {
                salt: hex("7ed5c3c2aeefd324a1cfb6edcacc26ee"),
                key: hex("2c1ea9601825e0a210c5b22bcbf592c18da7f913764e854a2cc6cadb96a34904"),
            },
            PublishedRound {
                salt: hex("7c5aec51ba4bf224492361cf0200d0f6"),
                key: hex("264a943b8c0820d8de629c662940dea48e62905bfff92ccef774db631b072b83"),
            },
            PublishedRound {
                salt: hex("8fe4f43c7bea7f92747c88188eed6127"),
                key: hex("3db8c5cdd567d3a73ab506023b6ff41959925eaba66a66e0bc971947f6b863c2"),
            },
            PublishedRound {
                salt: hex("869a787427ba920086c0f318c5db3267"),
                key: hex("1df92e057c1f5bdd0067cb72bdb461921e57dc9ce70e5f0489036b619a87864b"),
            },
            PublishedRound {
                salt: hex("14f7d436f8c906d2994dae203d6d3491"),
                key: hex("f1b922cd94a3639f770fabe58e7440237250239649519e11170f41496bc0474f"),
            },
            PublishedRound {
                salt: hex("c13bbd8c39a8118d84fb998b69927e44"),
                key: hex("59b0358111e4ed2a2dd21292ddae8fce4f6c6feeabd9bba536fecacda1e6e218"),
            },
            PublishedRound {
                salt: hex("2074fe5427f1356be67c24f0abde740f"),
                key: hex("3d9e66c9262e0ac310fd18f176d6769138181d34e2de76a14c61cbeb5c40ef1d"),
            },
            PublishedRound {
                salt: hex("5ec72e9c82a8e6ab21739092f4cb18dd"),
                key: hex("63b213f9689e14d35b4b1907fa306ee611e2e70ed57792fbb1d6f917bfee4626"),
            },
            PublishedRound {
                salt: hex("c77e2d473754d7c54a5e3af02fda261b"),
                key: hex("293d92c67804915716b5373fd15f19709aaf2486a30cc899a987adabef85e241"),
            },
            PublishedRound {
                salt: hex("e95f7b7a756a4b860a066753b0f336f5"),
                key: hex("98ce546a2132d0c2edabf8f5668f5b76e0f235411507e023436ca3097784aee7"),
            },
        ],
    },
    PublishedVector {
        name: "zero-12-memory-level-1",
        same_length: false,
        startup: false,
        phrase: "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about",
        password: "public test password",
        password_nfkd: b"public test password",
        pim: 0,
        memory_level: 1,
        container: "worry pigeon fix paper mad seminar piece glance repair crush approve salt mechanic recall okay denial ghost turkey swing private shop vague evidence cloud",
        recovery: &[
            PublishedReading {
                words: 12,
                verified: true,
                phrase: "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about",
            },
        ],
        rounds: [
            PublishedRound {
                salt: hex("888ae598b8e2ca06ecd96d4d0f8e7997"),
                key: hex("5a2ed82cd276481fd44eba676e0593c01fd2582976e1bff0e15cadc67a9727e6"),
            },
            PublishedRound {
                salt: hex("a18f3b91a9a6f2f5f86a4fa8edf76ff6"),
                key: hex("4c1ce13f0602d022236efa563e770a6d246d494cc7fcda206909c999b034fb89"),
            },
            PublishedRound {
                salt: hex("3f5125e44f6ee3f8c5b5bea1d883181f"),
                key: hex("4d2b94e6e870055f5760828a8b1ee4246c0acf08f9466ac83827dda25d5a176c"),
            },
            PublishedRound {
                salt: hex("5249a75af3d054db93b8562c46f410f6"),
                key: hex("a2612bb61533a3afd7616880c8155b0c1f8624f4928b1af1f174bb0e71d0c743"),
            },
            PublishedRound {
                salt: hex("f4697610d948ffdc1901e688fa3118f2"),
                key: hex("c0c725a85fe371968383f23e94b8141121b3a8ead6ac22edd71324fc96dd0201"),
            },
            PublishedRound {
                salt: hex("9cb55b66312dd7e07a0ce52cc944c949"),
                key: hex("6e280646b7434e570069032ef720f8320bc868315754a51cb62a379c91a63c57"),
            },
            PublishedRound {
                salt: hex("1e3e4d9a8459092c963b5b930393d339"),
                key: hex("0fc20406331f6bc0272307a6ff810f175d8aa4433abf096f507f26306a6b109b"),
            },
            PublishedRound {
                salt: hex("e3c2f3b7721378c80baccd0307b9bec3"),
                key: hex("083c7c6f31572782d51e97ed2106d1c8fe9e4e35a6416553c4c0bc0e4de893fc"),
            },
            PublishedRound {
                salt: hex("028f5831e602715983cd29bf2132c9a1"),
                key: hex("406ffaf96449f693c2df3331ee2c3fac5e1171fc4327af4635bc84c1ef5551a1"),
            },
            PublishedRound {
                salt: hex("4f3fcc83b4762a546472d19fe0a2d20d"),
                key: hex("c68224b1bddef2bfc8a1bbe37e069ce4f0ad27f6ffbe69bc20c1612d432895e7"),
            },
            PublishedRound {
                salt: hex("f0deae6eeb6da7741cfdd8de3962996b"),
                key: hex("053fa9d3f51a3cc64737e6728807b780ba3bc0952d7b043e609ec30ec82cd60f"),
            },
            PublishedRound {
                salt: hex("4bb4a97e62dfb8d891f5c72832585b3b"),
                key: hex("fbeefc11d630f3b74822602bef6054a61102cac903189539783af8bad20d43ea"),
            },
        ],
    },
    PublishedVector {
        name: "zero-12-pim-1-memory-level-1",
        same_length: false,
        startup: true,
        phrase: "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about",
        password: "public test password",
        password_nfkd: b"public test password",
        pim: 1,
        memory_level: 1,
        container: "grief pole beach apology three purse avoid gate nuclear another base scout always belt marine vocal aunt bird awake menu merit used hidden apple",
        recovery: &[
            PublishedReading {
                words: 12,
                verified: true,
                phrase: "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about",
            },
        ],
        rounds: [
            PublishedRound {
                salt: hex("697509d286b188aa5e38d1bc4e620995"),
                key: hex("1498de1d47ce636ec3dc2f6a2d6f879eb89e501067aa9906839ed3b7eb1d89f4"),
            },
            PublishedRound {
                salt: hex("59ac60ab9d6a819f94589b5b696efc4c"),
                key: hex("f0766c78441ab3ee00ca2d04774c8d2f2f0e350b169a5f17e144af7d3abca2e6"),
            },
            PublishedRound {
                salt: hex("332bed7471e2c69d822d833c974fde90"),
                key: hex("c897fdc86c1dc21fd5fb295919f1e6a8e9bc681e04f91dcbf818bc9be5a4ed04"),
            },
            PublishedRound {
                salt: hex("082ecd9e01616b9e4ce5412147e30f22"),
                key: hex("274c52f2fffc5118af51aa48a8467f2ea29bd0d4d1ca0a0b13160e722549b318"),
            },
            PublishedRound {
                salt: hex("2e32f944078305071c6a19801e888caa"),
                key: hex("a1d6997ab93ce7178dc79f00ae5621c6e101c2740cab52c845c93f36eb1a3cc6"),
            },
            PublishedRound {
                salt: hex("44b670a70256c0475790cadc8c6b4541"),
                key: hex("55653568be22af1e6bbda8e955a43533f4dfb7d4b6d509fbfb54ae4250d24394"),
            },
            PublishedRound {
                salt: hex("305989195b4174499a4bade1d60c3bba"),
                key: hex("6f3191366f5f2bc462635fcf16bc2d4d3720ccafb132dee3ee4fd400e7a3cb11"),
            },
            PublishedRound {
                salt: hex("19a2855d13213a86e38beead27a4e3f6"),
                key: hex("ec500e53418e28019dd4a77fc8508b9101015ca841c6ed52d2131c33ab1de729"),
            },
            PublishedRound {
                salt: hex("f39e0b4fb81383f2d711a8f223120761"),
                key: hex("f68c0f1f7cee3aa3e618fb07f8082d1d3237467e74453ea431288b065004cdf8"),
            },
            PublishedRound {
                salt: hex("bee16e03776672e5c2b16a4135e6f071"),
                key: hex("714a31974a9397e89ddb69116b4c38799c1a7e58e151eb0d16c6c4c285d803d4"),
            },
            PublishedRound {
                salt: hex("4c0745e687cfe38ccdfea9e5e976fe71"),
                key: hex("8fbcbef1480fd41ba53bd089c5ee47ae9fe734d4b05b96c89de8b9eb0af2b57f"),
            },
            PublishedRound {
                salt: hex("f81731d08c9ead6fa1651469bf215bde"),
                key: hex("078900f5dca99d05f183ef7cb7d04267242738c8fede37379801e987cefde638"),
            },
        ],
    },
    PublishedVector {
        name: "zero-12-pim-1",
        same_length: false,
        startup: false,
        phrase: "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about",
        password: "public test password",
        password_nfkd: b"public test password",
        pim: 1,
        memory_level: 0,
        container: "taste text dignity dove humble rhythm idle draw effort abuse expire model patch alert exist puzzle awesome holiday payment answer coffee mandate rice truly",
        recovery: &[
            PublishedReading {
                words: 12,
                verified: true,
                phrase: "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about",
            },
        ],
        rounds: [
            PublishedRound {
                salt: hex("a7fe04d215d6859e601e6510a208f8e2"),
                key: hex("476c6dd3693d7467a538cbf4285df4ad8fe841cd47e1cbd70e957552b32ff29b"),
            },
            PublishedRound {
                salt: hex("ab65bb466087d050a65f8942408d8f09"),
                key: hex("c67dce1503c2767c76e618ba580e0277bd9373d477c885c12a564cd202b91c7c"),
            },
            PublishedRound {
                salt: hex("e20b13282bd7d3d78cdfc20169e456bb"),
                key: hex("5745e582106025a71dfb12caeec6f1fd079dfcc12ba8eb248a2a80ada75e6b16"),
            },
            PublishedRound {
                salt: hex("4fcd38086890ce94dc2fc616eb2a4f9a"),
                key: hex("af445b0a87b9bcf42c58a60d898fe7651feb28aa12c6163230662140a5f613bd"),
            },
            PublishedRound {
                salt: hex("be68d12ed3ca666405a7c1f255363297"),
                key: hex("7af9596f25979b5b4e10ab8b9627a2e6733ad726776f9c8b9c94f06d7951761c"),
            },
            PublishedRound {
                salt: hex("bc4451f9b2a07d6181e0c454cd308570"),
                key: hex("5ab6fa20fe6be2ca3ce2f901f18a22d017f9177b125eb8d5d66fd491f3d712f4"),
            },
            PublishedRound {
                salt: hex("96773e7506ac9df2906af869cd674c67"),
                key: hex("e9db55c0cc83610009caa60cb5c084692aea651539f7400f5c22c60b4b86489d"),
            },
            PublishedRound {
                salt: hex("1792d9c6cd53e1c6b37bd4473229f0a2"),
                key: hex("64236261e4c04dd8bb8d3215103bc37ae7d421ebfdac35d0effb3178a9734866"),
            },
            PublishedRound {
                salt: hex("c7e86be0be2fadb48f0460d46afae614"),
                key: hex("caa5808b6e62c0fae283e320459a930ad458dde06030772fb88980a7427cbc9c"),
            },
            PublishedRound {
                salt: hex("e5df1226ec222df9c2ca9d1a12ed45d3"),
                key: hex("3e65b57c5b08e9bd3a7b48fae9eebc0c97e0e518ae4b66fd3d1ed963d3c35ad5"),
            },
            PublishedRound {
                salt: hex("40bfec5e79f0cee069522a2530e894f2"),
                key: hex("3d41c0a51a1ec7973b651d56659cd3a73ccad045c3e69e05129c03e6f1ed3036"),
            },
            PublishedRound {
                salt: hex("431e688464b8210f463ff1cfbaae5063"),
                key: hex("2329c755cc06f6e09b83e7d05615527b9f000e2170d08327f7d58b4fa7ba014c"),
            },
        ],
    },
    PublishedVector {
        name: "zero-12",
        same_length: false,
        startup: true,
        phrase: "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about",
        password: "public test password",
        password_nfkd: b"public test password",
        pim: 0,
        memory_level: 0,
        container: "donate stove tower picnic iron rescue trick shrimp roof rib home cigar bag pledge also nerve cycle famous provide heart ahead chunk caution peace",
        recovery: &[
            PublishedReading {
                words: 12,
                verified: true,
                phrase: "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about",
            },
        ],
        rounds: [
            PublishedRound {
                salt: hex("9d84a9f7b0fa2bfda1203a2afc48a6cf"),
                key: hex("54baa0776063dd8ca84ec97e15446b53d840fecb89d2319b6e90e6e60efe3824"),
            },
            PublishedRound {
                salt: hex("23fcca3501b76b20def8acb70aecb69e"),
                key: hex("960831f7043fae688d573628336a4b1acb4e83b55c58422bf455b93630b8ecd0"),
            },
            PublishedRound {
                salt: hex("875f9bb2d219b4027016e082fd359d9b"),
                key: hex("4b2f1b554f15dc852de7f09d5e181b8b867afba9545daf33aae8fea3a5dcf301"),
            },
            PublishedRound {
                salt: hex("defdcc07c50e7c0ac1e151aea2ea7e4c"),
                key: hex("43a20c515f08959e80693fda2a98b119ce78e564b6b60b6fd6c7877d2e0cba97"),
            },
            PublishedRound {
                salt: hex("38ff5f399df13b7ae429f169fdd1a753"),
                key: hex("6bdbf29d89f07799137409127f71bb56daafc52ff6913496388327cc546f57cd"),
            },
            PublishedRound {
                salt: hex("3ef429d94b989355b91db614ea2e7458"),
                key: hex("594371b43e17ca286a50b37a8f09b43ad6df17f3b0e2b0f4dc9be0bbf6685619"),
            },
            PublishedRound {
                salt: hex("4c855d465c3a6c29dbc24017a9885af6"),
                key: hex("5f94f3dd299e13e9b7c234241e8cb5a4ba56824f0b2432496b3e4c5b14feb138"),
            },
            PublishedRound {
                salt: hex("ae2f86ff2389129bb03eaec5e65c5390"),
                key: hex("86dc79d609f906d78d03eeefca81dba2b7d5e736f7eb39079c1a4874cb406a3a"),
            },
            PublishedRound {
                salt: hex("0eccba28797aac28934f2fdade63cbe9"),
                key: hex("8bfaf8742db0b6ad9c6a491e115d1817cffe7c19235dcabe59f0db9dcfb63ab4"),
            },
            PublishedRound {
                salt: hex("edb62114f0779e5d4b660eec6789bae8"),
                key: hex("63779f3b2d69a0468db46943e2ee12520f78aceb8c824257ab37081ee7be8e20"),
            },
            PublishedRound {
                salt: hex("37dc15b73af2ce3f4f74371397bedc4d"),
                key: hex("f646ad4a9d964b05c0837559bdf6d178a2ec9f4c9df36fbff3b857d0129531c1"),
            },
            PublishedRound {
                salt: hex("0624d118ee8eb2904ba935917a0b83b8"),
                key: hex("45408c3c1d283fb89971d219599357c50d55ed2cc20111c13b587c10cd9beaf7"),
            },
        ],
    },
    PublishedVector {
        name: "zero-15",
        same_length: false,
        startup: false,
        phrase: "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon address",
        password: "public test password",
        password_nfkd: b"public test password",
        pim: 0,
        memory_level: 0,
        container: "midnight vicious solution economy physical fat fabric arrest over theory throw sketch habit sting uncover staff hotel century pigeon sniff truth monkey fit crop",
        recovery: &[
            PublishedReading {
                words: 15,
                verified: true,
                phrase: "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon address",
            },
        ],
        rounds: [
            PublishedRound {
                salt: hex("18718c60aa4ccc3e56fd3d9850c9b1d5"),
                key: hex("09af6630073e5a7a7d47415f34c39dcfcbef85a279293b2062c8f6b455ba327a"),
            },
            PublishedRound {
                salt: hex("23f0ebdee1d0c1269a95c2eff77d84e2"),
                key: hex("b3e40e1b08fed54371e46bace545ebeffe413822989e451e980280f849c28874"),
            },
            PublishedRound {
                salt: hex("909f049356f9270e9fb59381a832d36d"),
                key: hex("3a76567996e2760d09476df8f9a0a6d1ae69fa963395a087de49ea696b96e6d4"),
            },
            PublishedRound {
                salt: hex("0efbe1a6255996e0ad4cdcb786ecad58"),
                key: hex("618d30e1d1fc432b4021e7a2a2b281bde354b29eed6ba8badb24ba6a3c57414d"),
            },
            PublishedRound {
                salt: hex("597ef42a9bf3e4cafe0a292f51c25083"),
                key: hex("d354053b19b62d77ad012ee378a637fd24868a3f05c787c3126b6df0278d5fd3"),
            },
            PublishedRound {
                salt: hex("33e1b8ab8fc9384c3be62f6e9be4c3bf"),
                key: hex("61fbbbad7076480f35e10c0936bb713694009f037c3693f94f84dc993f5af5c3"),
            },
            PublishedRound {
                salt: hex("e915da78d108b1ebd20fc26ad06a5251"),
                key: hex("267518fc1a44b3fd19560dfbbab5b0da3e6d4dc633f79bc33d4743758ffcf699"),
            },
            PublishedRound {
                salt: hex("17dd3699dbb675477fd3500410edbe31"),
                key: hex("0ebbf72cb4c0784ca726143f3e6b9aaf927bc62c710384919555d4da640fd48d"),
            },
            PublishedRound {
                salt: hex("99c0624c7fef19d40da8cd7b76a8faec"),
                key: hex("ac838f0a669014d106d13d3eee15b614a97a7a261009f2283f94a8fd46e9c4ec"),
            },
            PublishedRound {
                salt: hex("1c0c7f71386e33d9239226740a61df13"),
                key: hex("be7f19da8c4e5a4f790a834786b122d80ce7db3f16279bc6a702ec461c75354e"),
            },
            PublishedRound {
                salt: hex("20a146f6446c123693c9e0ced7866929"),
                key: hex("78d54e94574f2c2440c5ec7ded3e326c019191c9309f753f3b77da0808e4f5e3"),
            },
            PublishedRound {
                salt: hex("a84cfc6511832f00201abc74f40b3e55"),
                key: hex("dec85bf8b9e879d50a1608c95c9ca8c495c23484bf0be8a9275edc0aec11821d"),
            },
        ],
    },
    PublishedVector {
        name: "zero-18",
        same_length: false,
        startup: false,
        phrase: "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon agent",
        password: "public test password",
        password_nfkd: b"public test password",
        pim: 0,
        memory_level: 0,
        container: "stem omit entire powder broken mention liberty way culture legal truly merit stuff buzz rough soccer logic limit lucky boy syrup vintage reveal exist",
        recovery: &[
            PublishedReading {
                words: 18,
                verified: true,
                phrase: "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon agent",
            },
        ],
        rounds: [
            PublishedRound {
                salt: hex("c194d1c6870abef16bc35a43455122f8"),
                key: hex("ff72264acb7e16cedfa0b88c1fe98f93d42b8904a5254a84371dec62200df2e1"),
            },
            PublishedRound {
                salt: hex("c8590d3c42eb857107235056fce318c2"),
                key: hex("e7884d7165907487eac300cef8856a49bd1d0c2fcae35bd01eefa0de024b933f"),
            },
            PublishedRound {
                salt: hex("e5494e00701fe0128ce69e35f9f8fbfb"),
                key: hex("ddb7b2cbe2dd438b3300cb980ed3e1233fb157741560d4a7f42d20ad172a38c6"),
            },
            PublishedRound {
                salt: hex("a73e62bda693956d540d0f24e7860322"),
                key: hex("124c24238fa6a573a8e30da423abf6dd5a86a8b02c7a894f751d276d7ed0764a"),
            },
            PublishedRound {
                salt: hex("c1cfdd7ec10cba0893356e8833bb2608"),
                key: hex("c50114e7edd0be32aae53ba860384e89a0098e120c430b614b99101d0c7b8a5f"),
            },
            PublishedRound {
                salt: hex("37e6dc621df7f953f1afd6da6685177d"),
                key: hex("75c710dfae0ad3a06e8b1fe9b2482c2fa0425fbdba9821f93b385c1659a9f3b5"),
            },
            PublishedRound {
                salt: hex("b85ae10687a00b07e4f2016b77c0d62e"),
                key: hex("a462e19d7f044eceb3559a5eeeafc4a5b705686d512e1fee2d30d41ba6c7fc5f"),
            },
            PublishedRound {
                salt: hex("b411237219f4d3b6401719c90ad472ba"),
                key: hex("19ce5557b6413e12ee43450b9f6dd925ca444916daa6c40735b06d26674b869d"),
            },
            PublishedRound {
                salt: hex("fd3ca2a5328077ac9540e514533e06a4"),
                key: hex("4775326944933b03b7972bd74168ec414aea442371560eb9e1aec14c8fba6239"),
            },
            PublishedRound {
                salt: hex("09eb87e4bf3aa43ac63f18e2312f1fab"),
                key: hex("21dde508599799a154d0b97713b4eabb091bc3cbbef7640e8c1e2740fbd2180c"),
            },
            PublishedRound {
                salt: hex("e5cafbaa17d82c33353835db598500e2"),
                key: hex("ce2966ff446b96487c6a4834b3023446862d28a65dff8ae43ea8ebf3422b2ae4"),
            },
            PublishedRound {
                salt: hex("f00b27384582f7a162265a40e97d121e"),
                key: hex("5ecd6b28cdca4f68938f1012ac68f530a36b1ec8540f50a1ebc7bfa70e2930f7"),
            },
        ],
    },
    PublishedVector {
        name: "zero-21",
        same_length: false,
        startup: false,
        phrase: "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon admit",
        password: "public test password",
        password_nfkd: b"public test password",
        pim: 0,
        memory_level: 0,
        container: "mesh wasp horse cupboard replace harbor chest across obtain frequent pig clutch casino umbrella below wealth garden twin blanket fence monkey dirt truck brother",
        recovery: &[
            PublishedReading {
                words: 21,
                verified: true,
                phrase: "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon admit",
            },
        ],
        rounds: [
            PublishedRound {
                salt: hex("b863c5633741832a6979c4f5d299dd73"),
                key: hex("69280d0abab81ff80beb6d8ebf18c1b7678f81af7a89310dc93d850ae274fd94"),
            },
            PublishedRound {
                salt: hex("fba4b676ed7ba066bfe170ac84a51df6"),
                key: hex("e7b85883f3db5d84531f13b8bd68e9d9afd7b2869c6da7984a1990aed73ffe5b"),
            },
            PublishedRound {
                salt: hex("f9772c980ec74c6b60a9edb961d11cfb"),
                key: hex("daff5204d6ef530f5f7b402c1a31ed5e063a3ce75efdb1da4aba509cf7c2d02c"),
            },
            PublishedRound {
                salt: hex("80c7df45ed212ceabe0d2a65f5aa6711"),
                key: hex("4fbd7231c3826f38785a0e85da88e9295ab695745a4381cf4a390d979754a68e"),
            },
            PublishedRound {
                salt: hex("5d423ff3978b5920bddc3e54937e91ff"),
                key: hex("e6171f6ac83ec9d13ed665e5558bd8a857e39d37973bdf0e3ed43d9b52d7c6d2"),
            },
            PublishedRound {
                salt: hex("74359e063b9121bb0c136055060d2869"),
                key: hex("66f0fa95e7da1762dc6e33dd77d699afe2ad1f7577262572e4d798c01a4c3009"),
            },
            PublishedRound {
                salt: hex("601f4008c169f5889f5e3b5be762a33c"),
                key: hex("2428d817d7e5e386c96dbae1a29331b226dff2a4d0c0196d56f4548552591a7d"),
            },
            PublishedRound {
                salt: hex("b36ba219a998bf22d825689bccbdaa56"),
                key: hex("6dd1a0906b1492a2f1342358b3c00737c4175a53c4c9ec09640fe66b62f57ce2"),
            },
            PublishedRound {
                salt: hex("3544b6186f26b11937d95f40316424a5"),
                key: hex("b040741c3fc9b7c51d56a74c265037ebe64ab93d1dbc790ed8fb2a1d2a8cc0bc"),
            },
            PublishedRound {
                salt: hex("90126b3d3f1a8f1ba44d568387c51920"),
                key: hex("f8722d8284850436ac897f8607fa79c163d5608c0a05ad34a68c6e5fc3b0f509"),
            },
            PublishedRound {
                salt: hex("765d456d496fb4905c7a28400c1f8281"),
                key: hex("3e6de68ff53b4cc6d67cc1560858b5d1a7ce7846f41143be69c91bf65a0a2a61"),
            },
            PublishedRound {
                salt: hex("bf6de176f2f8370b32433a405a8f60dc"),
                key: hex("b4b239507a2ead5531e5220ad0d3cfae2d0896b11c43d61c7fd8f1a7a7ba00a4"),
            },
        ],
    },
    PublishedVector {
        name: "zero-24-pim-1-memory-level-1",
        same_length: false,
        startup: false,
        phrase: "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon art",
        password: "public test password",
        password_nfkd: b"public test password",
        pim: 1,
        memory_level: 1,
        container: "million glass couch neither visa story point zoo next actual example alarm edit fox dry assist obey broken slogan cattle boss suffer firm wonder",
        recovery: &[
            PublishedReading {
                words: 24,
                verified: false,
                phrase: "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon art",
            },
        ],
        rounds: [
            PublishedRound {
                salt: hex("1f001370c1124382ed512b662de6a8d5"),
                key: hex("dd8f3c4f280800c4f0ca00ac575b495c71c900b8357f42675a2c1a79644fd1d6"),
            },
            PublishedRound {
                salt: hex("3e2c416918c5e9de0ab12b6e6621f44c"),
                key: hex("286d0b9769d0c3140c03c3df62e6920101004d91efacda4fd260a930c55cc07a"),
            },
            PublishedRound {
                salt: hex("26ec3c056dd118967f710f73acfa9aea"),
                key: hex("a4f8eed14f24e67b41dde07035c9e1dfc5d038815c2743b36feb81c778e739e9"),
            },
            PublishedRound {
                salt: hex("cf8cab2f7b45e543441c92e28666aa02"),
                key: hex("02cdab1d592049a8b202b46efbef675554a195825dae389373634f3285c2da3e"),
            },
            PublishedRound {
                salt: hex("8decc8e6380ab8d6c80f5d65f01bfe6c"),
                key: hex("28d574678dfbc3c1cf5407301cfa01ec8d84dd2f69639e356f955baf355a796b"),
            },
            PublishedRound {
                salt: hex("2a1df4d0fb2c1b4f2c5213cfa0495209"),
                key: hex("7e216c3bbd52ed83969b668f328238eaf96a649b2e810afb6a07e2ca30af9ffd"),
            },
            PublishedRound {
                salt: hex("dd6680511f473ecc3b9d0f30394a64bc"),
                key: hex("dd2c74bd459531a8629f17133678aa7fe2558f9364686d3cebd00c18b62e93bf"),
            },
            PublishedRound {
                salt: hex("c2f9eb4b39586d3e7dad286579c34b18"),
                key: hex("73e8487dcfbe914caaae38411bd9d68ebd1213ab891743f27beb5f538092d4a8"),
            },
            PublishedRound {
                salt: hex("5a0fae0c06123884119a7021dd4153f0"),
                key: hex("a769a6248fea1a1d7e819a001ceb8b2706a73a9a8797e25ba6be2be4c17456be"),
            },
            PublishedRound {
                salt: hex("7fa92873aec42fce0043ee9eb24eed24"),
                key: hex("957c40deafd699c2f85611d34b0b7227452d092aa1c1820bb9ca15c3005c67cc"),
            },
            PublishedRound {
                salt: hex("6b19eb1002d9e8c953a99435d1213258"),
                key: hex("9080593bd675901b032fc41a5bbed9c3057d8768d30f92aa4e76d7f2063ba796"),
            },
            PublishedRound {
                salt: hex("6f76e6f4942d92ab02ba9214808b23fa"),
                key: hex("d5569b258f0b29d8394afa2f8e73c729f9bdc894265683f374d048891aacbeea"),
            },
        ],
    },
    PublishedVector {
        name: "zero-24",
        same_length: false,
        startup: true,
        phrase: "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon art",
        password: "public test password",
        password_nfkd: b"public test password",
        pim: 0,
        memory_level: 0,
        container: "win myth thrive loud year wall cargo cactus ring various coyote dinosaur wolf badge pencil strategy bachelor clarify series surround call grunt kit okay",
        recovery: &[
            PublishedReading {
                words: 24,
                verified: false,
                phrase: "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon art",
            },
        ],
        rounds: [
            PublishedRound {
                salt: hex("cd9178c37c54ec8b00c1a2f80b808c77"),
                key: hex("afe1fc30df1ba3cf38b4a67d88698fdb42ea329142c6310cb62983eff4edbf39"),
            },
            PublishedRound {
                salt: hex("54ced35ba2eef1ea5741f29d5284378f"),
                key: hex("560ca2f15ed172f0e377dc07b2ba38b6c3a043a4bcfca23e3e2e586620afcbd2"),
            },
            PublishedRound {
                salt: hex("a717e047e1d9e76735352ec0e3b3c63c"),
                key: hex("83c9d07b2d9c7bbf5b223bd575b803f6bc8e58ce9d7476a1bfc958da4b1dbab4"),
            },
            PublishedRound {
                salt: hex("42978eabe560722d0821aa24d8db7d7a"),
                key: hex("d47a775b365194edc4875d99b6dd6fd1ee7b26bcd7afb2ce6a1018a209e811eb"),
            },
            PublishedRound {
                salt: hex("b016ff39f7d2e1e86c5648e7fa942c6e"),
                key: hex("09925d16e813c8110b3be6fe63397c1a49b39ee4cd1323fd4a3a618a6d5e94ad"),
            },
            PublishedRound {
                salt: hex("2a31610a2092eecd1d36ac026839713b"),
                key: hex("104bd195007db77cc89061350064ab70387d6e0af1cf5504ae1ed204741434bc"),
            },
            PublishedRound {
                salt: hex("16b63c522c2a2071b6a900ac98ac65ee"),
                key: hex("fdda39d2abb09b60b0388b6d0327f515ad62fd9b1bc2958a2137e6564dae75e0"),
            },
            PublishedRound {
                salt: hex("7b2ccf785dba99aac60ca66da273689c"),
                key: hex("67f3e822780bead0c73759f799bb571766bd75070702cbc8a14cb81634d7929d"),
            },
            PublishedRound {
                salt: hex("02590cd414ed2ee0c6cf7b14c0070c04"),
                key: hex("5aebf123b6986e06aa66dab1b8924b27d5a2309010f1d3264cb6a35fa68fcaa1"),
            },
            PublishedRound {
                salt: hex("e14bd3da77bfbeb8bdc860ba2646d126"),
                key: hex("d619928cc95a9f61c6fa2f9a1a53324719f92439e6ad736421b41c5787992ce9"),
            },
            PublishedRound {
                salt: hex("ec34d271149ee6acb0da9552c12b2abe"),
                key: hex("89b3ecf111f1caa35f992bdf51416a2a570ef77dd4766953ce182aef8a91a0ab"),
            },
            PublishedRound {
                salt: hex("f821fa202779d22b667df0f0c2b2fcef"),
                key: hex("37997b4a3f444f2a6b243c8e2e531b334e0bd0833bc0f0d70f773175c7de70b7"),
            },
        ],
    },
    PublishedVector {
        name: "same-length-nonzero-12",
        same_length: true,
        startup: false,
        phrase: "legal winner thank year wave sausage worth useful legal winner thank yellow",
        password: "audit probe password 2026",
        password_nfkd: b"audit probe password 2026",
        pim: 0,
        memory_level: 0,
        container: "hotel supply dune casual fork treat century web wide vote steel media",
        recovery: &[
            PublishedReading {
                words: 12,
                verified: false,
                phrase: "legal winner thank year wave sausage worth useful legal winner thank yellow",
            },
        ],
        rounds: [
            PublishedRound {
                salt: hex("1cabaef5a9951a01d63ae8b61ffdfd41"),
                key: hex("ede043947ca8e16703b2a647299ee6ca3f7535e1bbecba6cc8071001318b6d66"),
            },
            PublishedRound {
                salt: hex("526794f588ea091eda085d908561d1b3"),
                key: hex("fa9e34da64c8cb98fd80c7195a40e0e936dd751f8263d1937fa5ea88afb3ab0d"),
            },
            PublishedRound {
                salt: hex("f69213080b266e3febb3d299447d6163"),
                key: hex("5a3b885b4e2cac1e75a7120e5b53e4695e0253223c3c41788fea88c0c258aead"),
            },
            PublishedRound {
                salt: hex("9c440648813402921b660c362af9bf8a"),
                key: hex("1b2b516f81ee8c92ee0b674bf2d5ae8bed554a3135f4a47734606c562083fb6c"),
            },
            PublishedRound {
                salt: hex("3699c584e58b50b7af8de565169c62ae"),
                key: hex("6d8e20d2eb2e47492bc284e0d6749c2dba1083004454b0f35f48491fd27fd11e"),
            },
            PublishedRound {
                salt: hex("4975b80c00f2e0d001fd44a1bec0d49b"),
                key: hex("731c6274d78c7ca2776ff36d4f29e0b89b611a947ba8010892b26a6e1a376b33"),
            },
            PublishedRound {
                salt: hex("3330847fa1b36e17bef0d901d41fd86c"),
                key: hex("637e0bea38a31a6ad7acf6281b07cfa357f619ff150ce94c8d00b015cd36d0a5"),
            },
            PublishedRound {
                salt: hex("80029ca6a44e08c9cf7ee33829127755"),
                key: hex("067cfaa53d66c80c8cde30b293a3150443ce626abcb4075ec619c50c5f6d2c20"),
            },
            PublishedRound {
                salt: hex("ec6d3b2dc050c6c71f26c0c3ea3f6d51"),
                key: hex("9ea35a41b65f3923215f36d0a5fcdf100adca85182eb3ec2f7363a27296de43c"),
            },
            PublishedRound {
                salt: hex("ca10999ffca9773b5bec0b34c95e5769"),
                key: hex("d822f602eb30f91206241800e464f6d46e341ac205fb8cb1a56c340d44cde3da"),
            },
            PublishedRound {
                salt: hex("ce7eb08ef334668ce6ad2c5632cec25f"),
                key: hex("3570a60d5f59c0f6a08a584502131801fe073a749b535a9470fbc0c0a23589af"),
            },
            PublishedRound {
                salt: hex("504eaab19e2c0217b1e577a6eb9d0fda"),
                key: hex("0db33c5474060d307a61d4b3b062d898417c996ce532bcf94a4d5a0f2d8e7e67"),
            },
        ],
    },
    PublishedVector {
        name: "same-length-nonzero-21",
        same_length: true,
        startup: true,
        phrase: "letter advice cage absurd amount doctor acoustic avoid letter advice cage absurd amount doctor acoustic avoid letter advice cage absurd apart",
        password: "audit probe password 2026",
        password_nfkd: b"audit probe password 2026",
        pim: 0,
        memory_level: 0,
        container: "seat govern run smooth flag fragile horse night simple luggage vacuum warfare tissue permit gym upset average blade pen blue view",
        recovery: &[
            PublishedReading {
                words: 21,
                verified: false,
                phrase: "letter advice cage absurd amount doctor acoustic avoid letter advice cage absurd amount doctor acoustic avoid letter advice cage absurd apart",
            },
        ],
        rounds: [
            PublishedRound {
                salt: hex("fb041b4f0ca51b3b43de726de7fe2583"),
                key: hex("bb7a85bc1a13649fccc6f65558266ea20e0cd15ee780c0122fe9a864afc86444"),
            },
            PublishedRound {
                salt: hex("313c3e0acbbbac0c8ec8a241e255a94a"),
                key: hex("af9a3d061178a27a64b280f1dcb6e7fc0949a920f80fe8178fe4a3326cb90391"),
            },
            PublishedRound {
                salt: hex("4e7cade56473604bb168636198f33683"),
                key: hex("5ef307a4b9841dd912563c871f9b263d4573935a6b63a4e59d6cf00e8653e85a"),
            },
            PublishedRound {
                salt: hex("fe2b366b322707b08fcc0d7a29acbae3"),
                key: hex("de4353c1051f1c581c746437bc646e16e9f0045737ceab5ddd915ba02a8912ab"),
            },
            PublishedRound {
                salt: hex("09c747ca0ef0581338d855d562472505"),
                key: hex("fd826710428768cd545ba50b820fd04ab8a1070f7142241ce14f49a362b53bf6"),
            },
            PublishedRound {
                salt: hex("ba122a5edd17263429cc59b8fc125f95"),
                key: hex("2ce97651139a8a55769ef7c4b68616374b3fcecb65920ac557473890a0021d3c"),
            },
            PublishedRound {
                salt: hex("30e0000d4e89f301cbb2f1727f4e04d4"),
                key: hex("0711e50dee5d3dfa774a8675f1a49eee5b1a85e2ff43081b4b7b205c587a5e86"),
            },
            PublishedRound {
                salt: hex("3456c567ee1bb6e6b6cb573bb276be40"),
                key: hex("7b51590b0641cbe6643b8aefcb875d7333fd679d0275d85712f973e3bc416b7a"),
            },
            PublishedRound {
                salt: hex("9749f5e4f7a0ab9a51b5e8e1efd13f92"),
                key: hex("0c0a9c54321e99f97c8c97d8f1c7b34c04acfebeee8d3569e2f355e96bd446d3"),
            },
            PublishedRound {
                salt: hex("e500b77b8f52b1417533e3f2e1943354"),
                key: hex("6cd4b4fccafde8365b49f74a361d515c20bf4f208daca4b47c6440dfabdc4f84"),
            },
            PublishedRound {
                salt: hex("b17d9ddc9bf72f5ae9ecd5170c3b9b1b"),
                key: hex("d206184bf3fb3eb312eccb9dfed4d1a1eee517babacc651fe505ba1f1e82e2dc"),
            },
            PublishedRound {
                salt: hex("df51c6e66fea31138f9566726461df18"),
                key: hex("c5dd226f3d374e1f331d3f99d8fed0320d896613d216ccfacb9df3a85df50902"),
            },
        ],
    },
    PublishedVector {
        name: "same-length-unicode-password",
        same_length: true,
        startup: true,
        phrase: "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon address",
        password: "Caf\u{e9} \u{fb01} \u{ff30}\u{212b}\u{2460} \u{1f510} \u{439}",
        password_nfkd: b"Cafe\xcc\x81 fi PA\xcc\x8a1 \xf0\x9f\x94\x90 \xd0\xb8\xcc\x86",
        pim: 0,
        memory_level: 0,
        container: "solve garlic flat nut marriage goat finger trade swap horror absent satoshi man inquiry finish",
        recovery: &[
            PublishedReading {
                words: 15,
                verified: false,
                phrase: "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon address",
            },
        ],
        rounds: [
            PublishedRound {
                salt: hex("b8fada32c7f901583b707a898cd19c83"),
                key: hex("f481e6992c74abba11176b234199bc9e5c7de5d5ae405377cb149bb341be14da"),
            },
            PublishedRound {
                salt: hex("ab51a1bad9fac5cfc55f9f3401b9ec2e"),
                key: hex("88b2f21c99059fda1fbd4646faafd07775d8086944cbf224f5dad2da9d71bb68"),
            },
            PublishedRound {
                salt: hex("da00cec409d4d423aaf31e9ea954334a"),
                key: hex("1a78114b21d075606f300d9c624ab1c84715fc8a807e987b76d46712705efb25"),
            },
            PublishedRound {
                salt: hex("3fdab1d2daa18f66459754f0217f6104"),
                key: hex("ab0fbf71fccd801a04b270b9e784e94ab4ff51a9c75fdb1cdc11a7d489d915ab"),
            },
            PublishedRound {
                salt: hex("b938b6e598ef06bda151ad24dd56450b"),
                key: hex("861763ab1693a4b47b09bbebeb962a98b931ab759b872cbecc66d860a276575c"),
            },
            PublishedRound {
                salt: hex("f1254b1d1dc00d3b8d222760dd7fcbd4"),
                key: hex("f5b0d1b2c442fbb0f99199cf3747c5f0d8778e1f4b52e0a73b930f5e7430affd"),
            },
            PublishedRound {
                salt: hex("2a836c8b2bf3856644f604c6beae8577"),
                key: hex("634685a9d8b8835d1f8196f3d3740095773e7181e1fc0fa93565177695802301"),
            },
            PublishedRound {
                salt: hex("576614f405c5bd4abe1457e6378c2254"),
                key: hex("96a0c5fc5bc49f806ea679d72462aa344176cc65e1994ec45e9c76e73e1f6032"),
            },
            PublishedRound {
                salt: hex("ab75c2edb80ef6b58567abc0d7bfdc3b"),
                key: hex("4f502e28bbb1e1ac7e14a3f773090a196a09df6f5a1e026642b06f5f1cdbc76b"),
            },
            PublishedRound {
                salt: hex("28ce04fc7571e69f61ffbc0b62a4a5c4"),
                key: hex("2e8a1b5856e299b1788bec8d77826a8a045fa2d7ae374f05b5595587227b5b21"),
            },
            PublishedRound {
                salt: hex("c0b9739b7230bf098cbbf4cc3c83570e"),
                key: hex("2cabd9dcdf5f47e960b5302add6634eb97025ac6864341175acb8ac5fd0364c3"),
            },
            PublishedRound {
                salt: hex("2c05ed9d4f3d53ff5fd40d4f4a07bd6a"),
                key: hex("ce6589f16923d9971a8b8141a982f3bc519c5242fc069243da9e8e9a44f0da40"),
            },
        ],
    },
    PublishedVector {
        name: "same-length-zero-12-memory-level-1",
        same_length: true,
        startup: false,
        phrase: "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about",
        password: "public test password",
        password_nfkd: b"public test password",
        pim: 0,
        memory_level: 1,
        container: "empty mutual unusual scene animal banner pact surprise erupt tank hood length",
        recovery: &[
            PublishedReading {
                words: 12,
                verified: false,
                phrase: "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about",
            },
        ],
        rounds: [
            PublishedRound {
                salt: hex("124db63559a02f703a313207f7095369"),
                key: hex("8b169c34a8f463779c20e004f9d028425ec942abddda826a90ae693e7a5cfd26"),
            },
            PublishedRound {
                salt: hex("b021dfb6fd9e551d6394caefaaa6ecfb"),
                key: hex("fb58e32512119d73ccbded61ba3d4f7fff5a4064307955f97bafa33532880da0"),
            },
            PublishedRound {
                salt: hex("dcfef596eb3edaa09af48e653cb48415"),
                key: hex("fbc3c86259b6e08f6043f52f72347c6c86b5d4b5e0fa7f7873f480db4d66e837"),
            },
            PublishedRound {
                salt: hex("f3c83a34de52587a91c2b164f41fbe72"),
                key: hex("645db3b32b7b2de56b6c92c2dfe4febdce4d50f0a75478e6b68c8b38dc4fc77b"),
            },
            PublishedRound {
                salt: hex("713c9c20d128330c684f87efc3fceea3"),
                key: hex("788cf8a28f9ea780a27a175cc1efff9be5e5098845416fc4bf70f47fd21b53d4"),
            },
            PublishedRound {
                salt: hex("5c2cd388b6fe13e1d022115bee3d1440"),
                key: hex("8ab815ca774a19b85b3ce564ae12e8ab8860e45cbf2dbfa6efb4af09d7f91ead"),
            },
            PublishedRound {
                salt: hex("a10d41996b654c94284b75729307f6cf"),
                key: hex("bc991da0bdf03e2707c69e8352f945cd0b9847df3fe3244647a44e60184f0336"),
            },
            PublishedRound {
                salt: hex("0353fc9aa1a05f041e515338ed1d3d3b"),
                key: hex("46803a115476be73be1f2305b63c682b52ddf324c1c099c40e32a28bca6f5f28"),
            },
            PublishedRound {
                salt: hex("ba5137426e863a2bc0e1bfc0eb7f4642"),
                key: hex("ea73a7370a332b4c538d8035dd20ced6674d70c4aa97e4edaf6c3236e72b91dd"),
            },
            PublishedRound {
                salt: hex("93ea98c9d7c702e3a4de200e609ce105"),
                key: hex("7d0557564879af6b327906a555e7ec3271eacaf4cdbd2ac483def26d926e5063"),
            },
            PublishedRound {
                salt: hex("4751bbab7b807627e417f4b1c1cf8be1"),
                key: hex("dfb99542f51c825d9d16dd6935b7c730d79b85498bab5e6d6c23f814a54430a4"),
            },
            PublishedRound {
                salt: hex("79d9de2a17b12b4449d366cece78daf8"),
                key: hex("56e6970630696d3181a714ddd7eb8780061547ad9feb75d8836f3b8b541a20e1"),
            },
        ],
    },
    PublishedVector {
        name: "same-length-zero-12-pim-1-memory-level-1",
        same_length: true,
        startup: false,
        phrase: "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about",
        password: "public test password",
        password_nfkd: b"public test password",
        pim: 1,
        memory_level: 1,
        container: "art gallery breeze cupboard patrol artist weasel point satisfy manual spread color",
        recovery: &[
            PublishedReading {
                words: 12,
                verified: false,
                phrase: "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about",
            },
        ],
        rounds: [
            PublishedRound {
                salt: hex("ed9fcf44d76af9bef9171c9fbe052c6b"),
                key: hex("4d27cc379fee8bf0d77be9509b65b89a703cd70a418516ee1f2ff5ec43f62b82"),
            },
            PublishedRound {
                salt: hex("fb2c2cce565e665eb971efdddb68a389"),
                key: hex("b4169303c084c23b5f894bf444aabc41d631a355ed8da29dcc8d09be0d52b698"),
            },
            PublishedRound {
                salt: hex("a8c32bd0a5b44d9ac50c1d56db9ad602"),
                key: hex("a0afa6e6b8bff4db07f633e1fd01b5886704fffeb9360c4faed4a62511269f78"),
            },
            PublishedRound {
                salt: hex("c3faa7fb4afc1402199f752600bcc5ec"),
                key: hex("cc93c3b9381809dc0e8fca42594b78104fea3fd776cf481ef51b3372d195f44c"),
            },
            PublishedRound {
                salt: hex("ad928cf1fe5023a3f6e21d07a055e5a9"),
                key: hex("1f3f5fb65642c330f1fe1c193f1e0a5cb2696073fdd107c0c8c2efa6f45a0428"),
            },
            PublishedRound {
                salt: hex("4b36fab4170ef910c0c6e4f6f2566ad0"),
                key: hex("1231894293d90fa7583a7f1309533ba1e548a83b679646a9701d2b4b03c65d12"),
            },
            PublishedRound {
                salt: hex("a6b64f2d1ae70f19e99a56ce6905a4b2"),
                key: hex("59edb62b6a28f754bc06f250675c59f6f271c44229539ec98d5fa5c949f1e949"),
            },
            PublishedRound {
                salt: hex("5469efd0cd5c4a739180de5228cf3747"),
                key: hex("58cbb2dabd78334f6aa3fdf6bf829a3d18b2d481c3fb8a37e35b8312b10f2b53"),
            },
            PublishedRound {
                salt: hex("d816b7fe91844880e6859997abb1f46a"),
                key: hex("174fb5447333847bf4be42291edc9cb6edd9d1733d1fe8f53fc0012cfb38f1d0"),
            },
            PublishedRound {
                salt: hex("0918790fe1735c435975089c93e4f699"),
                key: hex("6a20ef6dcba1086b10368d6724f4238245dc674c486c13040afaafdd3509f22a"),
            },
            PublishedRound {
                salt: hex("097d5701d9099378866f27c44351a73b"),
                key: hex("25290bb300ebb3d95b7532c21aae3a45735868ef9378de7cf0d22189b72d7d7a"),
            },
            PublishedRound {
                salt: hex("7478b4e15ae3f65eb2002157d8c2a767"),
                key: hex("02b42082325eb34fe1d5c5d209a000257fa507d3f888f872acea382461806cc4"),
            },
        ],
    },
    PublishedVector {
        name: "same-length-zero-12-pim-1",
        same_length: true,
        startup: false,
        phrase: "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about",
        password: "public test password",
        password_nfkd: b"public test password",
        pim: 1,
        memory_level: 0,
        container: "feed matrix crew doll tell accident alpha gorilla resemble guilt artwork farm",
        recovery: &[
            PublishedReading {
                words: 12,
                verified: false,
                phrase: "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about",
            },
        ],
        rounds: [
            PublishedRound {
                salt: hex("0b2ba321eec3aeea02aa35b3a426c5e6"),
                key: hex("33761573a5d4f1c0daf27a477c5a99bf4df8cd76115d2adb1d490189318b5af5"),
            },
            PublishedRound {
                salt: hex("e960215e1c9590705b7d9650aab67dd4"),
                key: hex("c8838eb4667d56f935e08edd2d06b2e93436af6a40e01325c7280121d456b535"),
            },
            PublishedRound {
                salt: hex("5ad0e88d10a3e12271830b30cec575f3"),
                key: hex("463b208ac79cc6401ffeaf0094beec10b24bffe18a9f9c663c70cdfb058ef255"),
            },
            PublishedRound {
                salt: hex("4bcb29051993af7144b89dbd144d2ad3"),
                key: hex("4ea627692c08a3153ff68eb78e2cee9d08fa15145cacf3eb99c40592d66712a2"),
            },
            PublishedRound {
                salt: hex("7e0753d67ca3f95dcbe0578e7f9ae75d"),
                key: hex("2052f63940582d4cfc3eabd0667de1c1ea821af7b1bb3d05c9ee56078aa05d02"),
            },
            PublishedRound {
                salt: hex("7bef02b894c5d391946ca802ea1cd988"),
                key: hex("98cc0d8bf7784237d8502fd95abdc1b8675db16aed6d4a9015e1a00035df6d0a"),
            },
            PublishedRound {
                salt: hex("beae8a7d279859ab387081e939ab7427"),
                key: hex("477ee798a323a8e6f9b2292ef8795d9180406d38366061ee9ee94d399a22158e"),
            },
            PublishedRound {
                salt: hex("6a4bc966871ce619acd233353a9c854a"),
                key: hex("e0903ea5a5b52a5c123dd9964412086b5ab4ac0a62ef0bb52d2a5b60a00637e3"),
            },
            PublishedRound {
                salt: hex("6382cacc60a22abc2615b8dc0a573b1a"),
                key: hex("8da92738922cefc537efa2c7d4ff6980a5f6e5ef4f4525c609c9f8e7765aa16d"),
            },
            PublishedRound {
                salt: hex("ee079019326160388fd33ad86cd86b11"),
                key: hex("8127614f76b6df46ca5149eed255bb615b799a5f88e1a013784a0428720d5efd"),
            },
            PublishedRound {
                salt: hex("97717644e7043fbd8bb043f994a88f59"),
                key: hex("76d4479286012e3589bc00ab8d4f52a5eb93a614502912f73e6ca17082dbb97e"),
            },
            PublishedRound {
                salt: hex("5a9bda974759984f20ac902dbd8a4ec8"),
                key: hex("214d1401f35b6b08b75f7d81c602fdabebdc2b4ceb61512bd427fc0764d0d5a2"),
            },
        ],
    },
    PublishedVector {
        name: "same-length-zero-12",
        same_length: true,
        startup: true,
        phrase: "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about",
        password: "public test password",
        password_nfkd: b"public test password",
        pim: 0,
        memory_level: 0,
        container: "renew alert there knife dose allow fashion casino kiwi lens sister bless",
        recovery: &[
            PublishedReading {
                words: 12,
                verified: false,
                phrase: "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about",
            },
        ],
        rounds: [
            PublishedRound {
                salt: hex("4d7cfb44c53037f2f429f58c6df85e36"),
                key: hex("507fecb28fbf81891871516a25e4628d38f68df57f24c0ca48f05bed601bcc96"),
            },
            PublishedRound {
                salt: hex("35139daed9f37f802be460d7403ae292"),
                key: hex("db3d3a92625560038743aa62073db983e104ad688fbacde0ddca80c95abb6193"),
            },
            PublishedRound {
                salt: hex("240171cf81012ac1b948e2525d3aa45a"),
                key: hex("5b5f249e3a752eca56f4cbb30f0e5ff660e04769fb5f207139e3ceca663b16b5"),
            },
            PublishedRound {
                salt: hex("73d0aed36ad6d408618ce53ffbec8a55"),
                key: hex("c1744840f9febc77ab130596e57dec3090414c602fd99ba606a0b29333b38fe1"),
            },
            PublishedRound {
                salt: hex("871ee3729b35060ce7561bf5918e27bd"),
                key: hex("ccae8a44040667228b66a792962a079aa3d57bd7b483fb63de04e3fa06531f37"),
            },
            PublishedRound {
                salt: hex("450bb6da48c24ae91c06ba6529490bfd"),
                key: hex("c2e239b43a67738cbd5eb3accd94bb89e0c003d0871ea8f07bb73fe4fa3ed980"),
            },
            PublishedRound {
                salt: hex("79cfba394f40ec3e46bc76cc8edaf446"),
                key: hex("810ba6073979a877608e584b7d78837ad81b6bb29c84162cf2cba8a7166df94e"),
            },
            PublishedRound {
                salt: hex("08468361c7e5b98e7fc583cd55a4ac93"),
                key: hex("b8e2595486b599f958c5dd68eb77f8bc4c10bd8ec3b93bbb3df7b2c2b0b9d3d9"),
            },
            PublishedRound {
                salt: hex("60ff4953663cf72893c4a562351d2420"),
                key: hex("9e4f5f077a9cf7e1de8dbaf4c1de72efa9811f35657a6f9b387450803f4d27e0"),
            },
            PublishedRound {
                salt: hex("ea3134713a0d2c29cadd76f0713399a9"),
                key: hex("7a7bdc088747e73882e84fa2da63282b01497dedeea0d960147d10b68e027da0"),
            },
            PublishedRound {
                salt: hex("2a60fc226dca1076294ea6e68ef75956"),
                key: hex("ef284b83c27080889e94f350a53a9ecc02c3022bfe3fe9564df697255778f7d6"),
            },
            PublishedRound {
                salt: hex("f0cb82be2199d407a793f45e3c40ef5e"),
                key: hex("ac42f81b07d4eb0dc29701c2c0550ea8c2765d4facf32ae79a4bf4e905148b30"),
            },
        ],
    },
    PublishedVector {
        name: "same-length-zero-15",
        same_length: true,
        startup: false,
        phrase: "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon address",
        password: "public test password",
        password_nfkd: b"public test password",
        pim: 0,
        memory_level: 0,
        container: "lyrics cage resemble oppose alert enroll kite cabbage lemon eager bike they twelve uniform boss",
        recovery: &[
            PublishedReading {
                words: 15,
                verified: false,
                phrase: "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon address",
            },
        ],
        rounds: [
            PublishedRound {
                salt: hex("b8fada32c7f901583b707a898cd19c83"),
                key: hex("ee5a4c3125ede0b1c055fc9a178213ee23e749ab7cd4097693b4120264e1bc64"),
            },
            PublishedRound {
                salt: hex("a2fd2573c29d465d9bc0195210297e51"),
                key: hex("b1781ccd17b84681e0dc1421225a801f3271fb685a2a1be32660e6701ed3ba40"),
            },
            PublishedRound {
                salt: hex("8d2490992c2ec1d57cebe688c02797a9"),
                key: hex("91ba3a093eaadb8cb8aed7912e5f870cc545ce740c211b38829c61ec800fc866"),
            },
            PublishedRound {
                salt: hex("9e56bcb8314aacb58ab748c800f002c6"),
                key: hex("f69f7048f59c428679beda2366d40feabee3d95a5742ffd2599fc974d27c1c52"),
            },
            PublishedRound {
                salt: hex("bfbb2a269aa847fad3040efb7bd6f24b"),
                key: hex("4dc5e327a92f4ebd5b43b5033a6055442c880fbf53e2142c78dbbd59ee245f6c"),
            },
            PublishedRound {
                salt: hex("b916c1bb503d43ac24506fbacf15c549"),
                key: hex("1d3f1572d253c474780199307b3c4b889cc573e0bd4e521a778b8e950a365b6b"),
            },
            PublishedRound {
                salt: hex("fdfb2078a44f6bd3165c06b800ba82e7"),
                key: hex("976d277490b8425ce721a88d9f73c20567026eede48c12ea65a6f4f52371cb0d"),
            },
            PublishedRound {
                salt: hex("c5464934bbafe3acfc39e517ae0d8049"),
                key: hex("cfde844f08c2e8745b83cf8fc6fb34097016343c0b882a720ca6f909da4f470c"),
            },
            PublishedRound {
                salt: hex("2290cb703169d10588a292172b793794"),
                key: hex("bba7bb0778f4059dd7ba72e3fe62d47279fe9e0b0fa55a0a7f7aaadca8b21696"),
            },
            PublishedRound {
                salt: hex("4e60c3cce41a3f1a45ac6bccd843f336"),
                key: hex("5be7a9cf35462ecd5912947750c28811ed45c0eb9cfd2fb9f81903c0641f72f6"),
            },
            PublishedRound {
                salt: hex("fa66e12d0915c93ec4898ae92ac7dfbe"),
                key: hex("4a589cd2f1b33f5cd5641543d76346699530cc66fe2b5d37d29288b0f422ad98"),
            },
            PublishedRound {
                salt: hex("c66a4bd60fe8cb82fe707360ff2b1cd7"),
                key: hex("fe230096bd01ccef9d1dbe512f1964073fe174f28ae05ad63f656f6288b6df27"),
            },
        ],
    },
    PublishedVector {
        name: "same-length-zero-18",
        same_length: true,
        startup: true,
        phrase: "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon agent",
        password: "public test password",
        password_nfkd: b"public test password",
        pim: 0,
        memory_level: 0,
        container: "afraid isolate replace tennis release cash blade sketch truck goat blind dentist borrow smooth snap essence decline awesome",
        recovery: &[
            PublishedReading {
                words: 18,
                verified: false,
                phrase: "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon agent",
            },
        ],
        rounds: [
            PublishedRound {
                salt: hex("281586f8288cbad6072aad19582473fd"),
                key: hex("72e730115e6f32ba1127556c86c7bfaff8c45a999d6c6e09092a8afc35083119"),
            },
            PublishedRound {
                salt: hex("0c1c0237e7c3107f13b645a3c1700b20"),
                key: hex("953e4627fd3b5bc297bdc4c30285eef9bd985db6c3b578c539638d959e2f7091"),
            },
            PublishedRound {
                salt: hex("278bb4932fc13fdcb478c56f627df024"),
                key: hex("01eb0eedb41b2b59454523d6c652305cb2272ff211a260c9e23800cd0d37168e"),
            },
            PublishedRound {
                salt: hex("b78d46d5c994e0cc190f1213e2afafda"),
                key: hex("0f57103fde82fde491ba2891607e5d7257eca1ee627c48fae6213ad6f6b59003"),
            },
            PublishedRound {
                salt: hex("5d9484b67714c5d49a651f020cff2085"),
                key: hex("6ccf0857ae92a4ea71a50bcc40be9a6d06525892bf3dab31771fb4df5e829080"),
            },
            PublishedRound {
                salt: hex("0ac51611f9bcb520ebc85edd11477c8d"),
                key: hex("91cfd1446051cea5e64fb38dc63bc1b6e21b68bf0fbfe13f933d6335158da46d"),
            },
            PublishedRound {
                salt: hex("afdb23745d7f9d795cc2c0e23544d8ff"),
                key: hex("0912bade12e32b7cc0e733d613c491b89eae30d5159bc55b9acc0aef37dd20f4"),
            },
            PublishedRound {
                salt: hex("b979989fcf5b618482d1f6d6eb0017d0"),
                key: hex("6c5d428a87c8a1ae81582c0d631355aefde6e831de31bbd164ecfab5dc1bc627"),
            },
            PublishedRound {
                salt: hex("ad1847ab155223d2de6003f95bf0c5c9"),
                key: hex("ad8263d3663bff5cf7b5a25f59bfeaea251e9251944a847f60ef4ca889915760"),
            },
            PublishedRound {
                salt: hex("b6d9753e77af2c0800cefe04429ea6cc"),
                key: hex("e9d6ac677a1da97c310bea6215b5cc199e5c1a0d7ce8c7ed34208a9254ddabab"),
            },
            PublishedRound {
                salt: hex("1c07f5c0d96e9b419c14668ea22305f9"),
                key: hex("11dc71430700d081c5e96dd4f1fabbb237dcabb7f9a3a8af2e79e69f12c407c8"),
            },
            PublishedRound {
                salt: hex("682886f71214cda8758402d281d143d1"),
                key: hex("9975f5d28f854fe198474b7ce04a18ddb6074d49302b958b7663dc265f8ffb1b"),
            },
        ],
    },
    PublishedVector {
        name: "same-length-zero-21",
        same_length: true,
        startup: false,
        phrase: "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon admit",
        password: "public test password",
        password_nfkd: b"public test password",
        pim: 0,
        memory_level: 0,
        container: "jeans year purpose original fragile zero slush bean crew rescue flame magnet unusual heart slush arrange jungle novel mansion iron august",
        recovery: &[
            PublishedReading {
                words: 21,
                verified: false,
                phrase: "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon admit",
            },
        ],
        rounds: [
            PublishedRound {
                salt: hex("4aab05e292c71e9474ed32ac5ce8d57e"),
                key: hex("f8129b45c1df61f80f66143d5c8fbbfa55656c76733f0daa5e72e447b816bacb"),
            },
            PublishedRound {
                salt: hex("1a2ee3efac6abf44424c23655f88ccdc"),
                key: hex("e1dae9597498e6974d6a7f5883d921344ac99d77734f9660f78df4d0d5c35f2e"),
            },
            PublishedRound {
                salt: hex("136edf70d0701e36068095c717c0c2cd"),
                key: hex("cb57b316d60d7da7801431f1cc8244ee45fdad32722c895fc82b429e04433649"),
            },
            PublishedRound {
                salt: hex("2027e6db8920c01421ec6d9e15006f2b"),
                key: hex("4ee7417188a65b84f7e38a28558cf678e57aa4e0590e9c6ed425781bc065a5ea"),
            },
            PublishedRound {
                salt: hex("6759a8c73822a5558c7e9795e8828dcb"),
                key: hex("48a5ad1657b8eeb987f62cacb919102f1b9e561e1df331477e1e79c6b55d658a"),
            },
            PublishedRound {
                salt: hex("44855907a36defbc9db0fbbaf9bf443c"),
                key: hex("01e390864ded541d00966aa3f41f9f5f5d35caf7e097edfaf68291e56b032657"),
            },
            PublishedRound {
                salt: hex("e62d9d889f01bebe24a8aa104a2f8eb5"),
                key: hex("fbb309093d91d040dda5bd9bb9650a9bd7cb9936b9818ab33332bd2d2e30538b"),
            },
            PublishedRound {
                salt: hex("f8adfd0ce2b32dc6b03d14740e12aa30"),
                key: hex("68a7e863c9f9906d87d483d52183b3edba9a7d6f24438caa3017fe09ba47721d"),
            },
            PublishedRound {
                salt: hex("1971a70f5023f9604009321ffb93e4b7"),
                key: hex("eed1ff25889f0d5b158833a15b9cbbf02f9567d84a5984a04262226ae07e98cc"),
            },
            PublishedRound {
                salt: hex("3290f3356cf1edbee48c0b7f20c72378"),
                key: hex("b981c2b54bc26e2b43dc511657b8ac91c32f417baf4cf2492fc397839a8dd0b1"),
            },
            PublishedRound {
                salt: hex("b61160157996a74443365ac27e4eb7cc"),
                key: hex("2051ed5ba49d94a9f68075e57cdbd0d89a956e9320156656c4092fee947f1f45"),
            },
            PublishedRound {
                salt: hex("4f85711ab2fce1283d6a8afa49e02541"),
                key: hex("45279ddd623d13f3df16f9eb5ae031ed6a22e9e56a0b4ced2a758f1863ce5071"),
            },
        ],
    },
];
