#!/usr/bin/env python3
"""Writes src/mhfe/published_rounds.rs from the published vectors in tests/fixtures.

The self-checks replay every published vector through the library with the round keys the vector
records (src/mhfe/known_answers.rs), so they need each vector's inputs, container, recovery and the
salt and Argon2id key of each of its twelve rounds. This script copies exactly those values; it
computes nothing. The output is deterministic: the same fixtures give the same bytes. The unit test
published_round_table_equals_the_fixtures compares every value with the fixtures again.

Usage: python3 scripts/generate-published-rounds.py [--check]
With --check the script writes nothing and fails when the file differs from its output.
"""

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "src" / "mhfe" / "published_rounds.rs"
SUITES = [
    ("suite3-vectors", False),
    ("suite4-vectors", True),
]
# The vectors of the startup check: every phrase length's packing in either suite, both
# settings, a non-ASCII password, the repair words and the ambiguous reading. The others run in
# the full self-test only.
STARTUP = [
    "zero-12",
    "nonzero-15",
    "zero-24",
    "ambiguous-12-21",
    "unicode-password",
    "zero-12-pim-1-memory-level-1",
    "same-length-zero-12",
    "same-length-unicode-password",
    "same-length-zero-18",
    "same-length-nonzero-21",
]
ROUNDS = 12


def rust_text(text):
    """A Rust string literal that keeps the source ASCII: every other character is escaped."""
    out = []
    for character in text:
        if character in '"\\':
            out.append("\\" + character)
        elif " " <= character <= "~":
            out.append(character)
        else:
            out.append("\\u{%x}" % ord(character))
    return '"' + "".join(out) + '"'


def rust_bytes(hex_text):
    """A Rust byte string literal of the bytes `hex_text` gives, printable ASCII kept."""
    out = []
    for byte in bytes.fromhex(hex_text):
        character = chr(byte)
        if character in '"\\':
            out.append("\\" + character)
        elif 0x20 <= byte <= 0x7E:
            out.append(character)
        else:
            out.append("\\x%02x" % byte)
    return 'b"' + "".join(out) + '"'


def vectors():
    """Every published vector of both suites, in file-name order within each suite."""
    found = []
    for folder, same_length in SUITES:
        for path in sorted((ROOT / "tests" / "fixtures" / folder).glob("*.json")):
            vector = json.loads(path.read_text(encoding="utf-8"))
            if not isinstance(vector, dict) or "inputs" not in vector:
                continue  # the negative cases and the verification records
            found.append((vector, same_length))
    return found


def readings(vector, same_length):
    recovery = vector["recovery"]
    if same_length:
        recovery = [recovery]
    return [(reading["words"], reading["verified"], reading["phrase"]) for reading in recovery]


def rounds(vector):
    encryption = vector["encryption"]["rounds"]
    if len(encryption) != ROUNDS:
        raise SystemExit(f"{vector['name']}: {len(encryption)} rounds")
    return [(entry["salt_hex"], entry["argon2_key_hex"]) for entry in encryption]


def render():
    published = vectors()
    names = [vector["name"] for vector, _ in published]
    missing = [name for name in STARTUP if name not in names]
    if missing:
        raise SystemExit(f"startup vectors not found: {missing}")
    lines = [
        "//! The published MHFE vectors as the self-checks replay them: inputs, container, recovery and",
        "//! the salt and Argon2id key of every round. Generated by scripts/generate-published-rounds.py",
        "//! from tests/fixtures/suite3-vectors and tests/fixtures/suite4-vectors (the specification's",
        "//! vectors/suite3 and vectors/suite4); do not edit. The unit test",
        "//! published_round_table_equals_the_fixtures compares every value with the fixtures.",
        "",
        "use super::known_answers::{PublishedReading, PublishedRound, PublishedVector};",
        "use crate::self_check::hex;",
        "",
        f"pub(super) static PUBLISHED: [PublishedVector; {len(published)}] = [",
    ]
    for vector, same_length in published:
        inputs = vector["inputs"]
        lines += [
            "    PublishedVector {",
            f"        name: {rust_text(vector['name'])},",
            f"        same_length: {'true' if same_length else 'false'},",
            f"        startup: {'true' if vector['name'] in STARTUP else 'false'},",
            f"        phrase: {rust_text(inputs['phrase'])},",
            f"        password: {rust_text(inputs['password'])},",
            f"        password_nfkd: {rust_bytes(inputs['password_nfkd_utf8_hex'])},",
            f"        pim: {inputs['pim']},",
            f"        memory_level: {inputs['memory_level']},",
            f"        container: {rust_text(vector['container'])},",
            "        recovery: &[",
        ]
        for words, verified, phrase in readings(vector, same_length):
            lines += [
                "            PublishedReading {",
                f"                words: {words},",
                f"                verified: {'true' if verified else 'false'},",
                f"                phrase: {rust_text(phrase)},",
                "            },",
            ]
        lines += ["        ],", "        rounds: ["]
        for salt, key in rounds(vector):
            lines += [
                "            PublishedRound {",
                f'                salt: hex("{salt}"),',
                f'                key: hex("{key}"),',
                "            },",
            ]
        lines += ["        ],", "    },"]
    lines += ["];", ""]
    return "\n".join(lines)


def main(arguments):
    text = render()
    if arguments == ["--check"]:
        if OUTPUT.read_text(encoding="utf-8") != text:
            raise SystemExit(f"{OUTPUT.relative_to(ROOT)} differs from the fixtures; regenerate it")
        return
    if arguments:
        raise SystemExit(__doc__)
    OUTPUT.write_text(text, encoding="utf-8")


if __name__ == "__main__":
    main(sys.argv[1:])
