#!/usr/bin/env python3
"""Writes src/bin/mhfe/cell_widths.rs: the terminal cells a character takes, from Unicode 17.0.0.

The line editor of the command-line tool moves the cursor by the cells each typed character takes
(src/bin/mhfe/typed_line.rs), so that a wide character, such as a CJK ideograph or an emoji, and a
combining mark put it in the right column (AUD-016-UI001, AUD-018). The rule is the one terminals
follow, after Markus Kuhn's wcwidth:

- two cells: East_Asian_Width W (wide) or F (fullwidth), which includes the emoji shown as emoji;
- no cell: the combining marks (General_Category Mn and Me), the format characters (Cf) other
  than the soft hyphen U+00AD, and the Hangul Jamo vowels and final consonants (U+1160 to U+11FF,
  U+D7B0 to U+D7C6, U+D7CB to U+D7FB), which join the syllable before them;
- one cell: everything else.

The model is the per-character width of glibc's wcwidth and GLib (VTE terminals), which xterm and
most Linux terminals follow. Terminals that measure whole grapheme clusters (kitty, WezTerm, foot,
Windows Terminal) can differ for emoji sequences, such as a variation selector or a skin-tone
modifier; the line editor shows no zero-width joiner, so such sequences stay apart.

The character data come from `unicodedata2` 17.0.1, which holds the Unicode 17.0.0 database, the
Unicode version of the password rule (scripts/independent-suite3-requirements.txt pins it with its
hash), not from Python's own `unicodedata`, which is older. The output is deterministic: the same
Unicode version gives the same bytes.

Usage: python3 scripts/generate-cell-widths.py [--check]
With --check the script writes nothing and fails when the file differs from its output.
"""

import sys
from pathlib import Path

try:
    import unicodedata2 as unicode17
except ImportError:
    sys.exit(
        "Needs unicodedata2: python3 -m pip install --require-hashes "
        "-r scripts/independent-suite3-requirements.txt"
    )

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "src" / "bin" / "mhfe" / "cell_widths.rs"
UNICODE_VERSION = "17.0.0"
# One past the last code point.
CODE_POINTS = 0x110000
SURROGATES = range(0xD800, 0xE000)
SOFT_HYPHEN = 0x00AD
# Hangul Jamo medial vowels and final consonants, which join the syllable before them: the Jamo
# block's and those of Hangul Jamo Extended-B (Hangul_Syllable_Type V and T there), as glibc and
# GLib count them.
HANGUL_JAMO_JOINING = (range(0x1160, 0x1200), range(0xD7B0, 0xD7C7), range(0xD7CB, 0xD7FC))


def cells(code_point):
    character = chr(code_point)
    category = unicode17.category(character)
    if category in ("Mn", "Me") or any(code_point in run for run in HANGUL_JAMO_JOINING):
        return 0
    if category == "Cf" and code_point != SOFT_HYPHEN:
        return 0
    if unicode17.east_asian_width(character) in ("W", "F"):
        return 2
    return 1


def ranges():
    """The runs of code points that do not take one cell, as (first, last, cells)."""
    runs = []
    for code_point in range(CODE_POINTS):
        if code_point in SURROGATES:
            continue
        width = cells(code_point)
        if width == 1:
            continue
        if runs and runs[-1][1] == code_point - 1 and runs[-1][2] == width:
            runs[-1] = (runs[-1][0], code_point, width)
        else:
            runs.append((code_point, code_point, width))
    return runs


def render():
    runs = ranges()
    lines = [
        "// Generated by scripts/generate-cell-widths.py from Unicode {}; do not edit.".format(
            UNICODE_VERSION
        ),
        "",
        "//! The terminal cells of the characters that do not take one: runs of code points, in",
        "//! order, with no cell (combining marks, format characters, joining Hangul Jamo) or two",
        "//! (East Asian wide and fullwidth, emoji among them). Every other character takes one.",
        "",
        "/// The Unicode version of the table, the version of the password rule; the tests compare",
        "/// it with the one the password rule's normalization has.",
        "#[cfg(test)]",
        "pub const UNICODE_VERSION: (u8, u8, u8) = ({});".format(
            ", ".join(UNICODE_VERSION.split("."))
        ),
        "",
        "/// (first, last, cells) of each run, sorted and not overlapping. One run a line, as the",
        "/// generator writes it, which rustfmt would otherwise pack.",
        "#[rustfmt::skip]",
        "pub const RUNS: [(u32, u32, u8); {}] = [".format(len(runs)),
    ]
    lines += ["    (0x{:X}, 0x{:X}, {}),".format(first, last, width) for first, last, width in runs]
    lines += ["];", ""]
    return "\n".join(lines)


def main():
    if unicode17.unidata_version != UNICODE_VERSION:
        sys.exit(
            "unicodedata2 has Unicode {}, the table needs {}".format(
                unicode17.unidata_version, UNICODE_VERSION
            )
        )
    text = render()
    if "--check" in sys.argv[1:]:
        if OUTPUT.read_text(encoding="utf-8") != text:
            sys.exit("{} differs from its generator's output".format(OUTPUT.relative_to(ROOT)))
        print("{} matches Unicode {}".format(OUTPUT.relative_to(ROOT), UNICODE_VERSION))
        return
    OUTPUT.write_text(text, encoding="utf-8")
    print("wrote {}".format(OUTPUT.relative_to(ROOT)))


if __name__ == "__main__":
    main()
